# base configuration
baseURL: 'https://adrielperkins.dev'
languageCode: 'en-us'
title: 'Adriel Perkins - DevOps, Dev, & Tech'
MetaDataFormat: 'yaml'
theme: "dev-resume-blog"


#  params

params:
    plugins:
        js:
            - link: plugins/typedJS/typed.js
            - link: js/site.js
        css:
            - link: "plugins/css/custom.css"
    copyright: "copyright &copy; 2020 - Adriel Perkins - All Rights Reserved"
    logo: images/ap-logo.svg
    author: "Adriel Perkins"
    social:
        - identifier: instagram
          URL: "https://instagram.com/adrielperkins"
          icon: "fab fa-1x fa-instagram"
        - identifier: twitter
          URL: "https://twitter.com/adrielqp"
          icon: "fab fa-1x fa-twitter"
        - identifier: facebook
          URL: "https://facebook.com/adrielperkins"
          icon: "fab fa-1x fa-facebook-f"
        - identifier: github
          URL: "https://github.com/adrielp"
          icon: "fab fa-1x fa-github"
        - identifier: youtube
          URL: "https://www.youtube.com/channel/UCMvC5sEUUx4U5CsM24Egmhg?view_as=subscriber"
          icon: "fab fa-1x fa-youtube"
        - identifier: behance
          URL: "https://www.behance.net/adrielperkins"
          icon: "fab fa-1x fa-behance"
        # - identifier: paypal
        #   URL: ""
        #   icon: "fab fa-paypal"
        # - identifier: patreon
        #   URL: ""
        #   icon: "fab fa-patreon"


menu:
    main:
        - identifier: home
          URL: "/"
          name: "Home"
          weight: 1
        - identifier: blog
          URL: "blog"
          name: "Blog"
          weight: 2
        - identifier: projects
          URL: "projects"
          name: "Projects"
          weight: 3
        - identifier: resume
          URL: "resume"
          name: "Resume"
          weight: 4
        - identifier: contact
          URL: "contact"
          name: "Contact"
          weight: 5
