version: "3.8"


services:
  nginx:
    build:
      context: "."
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adriel.rule=Host(`adrielperkins.docker.localhost`)"
      # - "traefik.http.routers.adriel.entrypoints=websecure"
      # - "treafik.http.routers.adriel.tls.certresolver=myhttpchallenge"
    # ports:
    #   - "9090:80"
    # volumes:
    #   - "/Users/adriel/Development/repos/apdev-hugo/adrielperkins.dev/public:/usr/share/nginx/html:ro"
    #   - "/Users/adriel/Development/repos/apdev-hugo/adrielperkins.dev:/etc/nginx"

