# This is a basic workflow to help you get started with Actions

name: Deploy Site

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy: 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Tar Public Folder For Archive
        run: |
          tar -cvf public.tar $GITHUB_WORKSPACE/adrielperkins.dev/public

      - uses: actions/upload-artifact@v2
        with:
          name: public.tar 
          path: public.tar

      - name: Destroy Public Folder On Server
        uses: fifsky/ssh-action@master
        with:
          command: |
            rm -rf adrielperkins.dev/public
          host: ${{ secrets.REMOTE_HOST }}
          user: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy Site To Server
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rltgoDzv0 --delete"
          SOURCE: adrielperkins.dev/public 
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.SITE_TARGET }}

      - name: Deploy WebServer
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rltgoDzv0 --delete"
          SOURCE: webserver/ 
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.WEB_SERVER_TARGET }}

      - name: Recreate Site On Server
        uses: fifsky/ssh-action@master
        with:
          command: |
            mv webserver/docker-compose.prod.yaml /home/adriel/docker-compose.prod.yaml
            docker-compose -f docker-compose.prod.yaml build 
            docker-compose -f docker-compose.prod.yaml up -d 
          host: ${{ secrets.REMOTE_HOST }}
          user: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
