# This is a basic workflow to help you get started with Actions

name: Build and Deploy Site

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Hugo
        run: brew install hugo

      - name: Build Site
        run: |
          cd $GITHUB_WORKSPACE/adrielperkins.dev
          hugo -e production --minify --cleanDestinationDir

      - name: List Contents
        run: |
          cd $GITHUB_WORKSPACE/adrielperkins.dev
          ls -alt
          ls -altr public/

      - name: Tar Public Folder For Archive
        run: |
          tar -cvf public.tar $GITHUB_WORKSPACE/adrielperkins.dev/public

      - uses: actions/upload-artifact@v2
        with:
          name: public.tar 
          path: public.tar

      - name: Reset To Home Directory 
        run: |
          cd ~

      - name: Deploy Site To Server
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rltgoDzv0 --delete"
          SOURCE: adrielperkins.dev/public 
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.SITE_TARGET }}

      - name: Deploy WebServer
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rltgoDzv0 --delete"
          SOURCE: webserver/ 
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.WEB_SERVER_TARGET }}
